# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PanoramaViewer
                                 A QGIS plugin
 Плагин для просмотра 360° панорам и отображения точек-мест, в которых они были сняты
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-26
        copyright            : (C) 2023 by Pavel Pereverzev
        email                : pasha004@yandex.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PanoramaViewer class from file PanoramaViewer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .panorama_viewer import PanoramaViewer
    return PanoramaViewer(iface)
